name: CI
on: [push]
jobs:
  test:
    runs-on: macos-10.15
    strategy:
      matrix:
        project: ['Quiz']
    steps:
      - uses: actions/checkout@v2
      - run: cd ${{ matrix.project }}
      - run: xcodebuild test -enableCodeCoverage YES -scheme ${{ matrix.project }} -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 11' ONLY_ACTIVE_ARCH=NO
      - run: cd ..