name: CI
on: [push]
jobs:
  test:
    runs-on: macos-10.15
    strategy:
      matrix:
        project: ['Quiz']
    steps:
      - uses: actions/checkout@v2
      - name: Run build script
        run: ./.github/scripts/build.sh
        shell: bash